[workspace]
members = [
	"snv",
	"snvp",
	"snvc",
	"snvi",
]

[workspace.package]
authors = ["SchokiCoder <afschoknecht@gmail.com>"]
repository = "https://github.com/SchokiCoder/sandvich"
version = "0.0.0"
edition = "2021"
license = "GPLv3"
publish = false

